project:
  type: website
  resources:
    - icons

website:
  title: ""
  site-url: https://zakiya.github.io/nwsl-schedule/_site
  search: false
  navbar:
    background: light
    foreground: dark
    left:
      - text: "This Week"
        href: index.qmd
      - text: "Full Schedule"
        href: schedule.qmd


format:
  html:
    theme: lux
    css: styles.css
    include-after-body: scripts.html
    include-in-header: head.html
    toc: true
    page-layout: article
