---
title: "How to Watch"
---

## [NWSL+](https://www.nwslsoccer.com/plus)

NWSL+ streams live NWSL games, match recaps, and highlights. It's free online, and on the NWSL+ app on Apple TV, Fire TV, and Roku.

## [CBS](https://www.cbs.com/)

CBS games can be watched on your local CBS affiliate (over-the-air or via cable/satellite). Streaming on [Paramount+](https://www.paramountplus.com/) is only available on the **Paramount+ with SHOWTIME (Premium)** plan. The cheaper Paramount+ Essentials plan does not include live local CBS streams.No matches are streaming-only on Paramount+. This is a change from prior seasons.

## [CBS Sports Network (CBSSN)](https://www.cbssportsnetwork.com/)

You typically need cable or streaming subscription to watch CBSSN. You can search for TV Providers by zipcode at the [CBS Sports Network website](https://www.cbssportsnetwork.com/#channel-finder).

## [Victory+](https://victoryplus.com/)

Victory+ is the newest streaming partner of the NWSL. It's a free for live streaming and on-demand sports entertainment across major platforms.

After you've created a [Victory+ account](https://victoryplus.com/), you can download the Victory+ app on your smart TV and [pair your account](victoryplus.com/settings/pair).

 [National Women's Soccer League's Victory+ FAQ site](https://www.nwslsoccer.com/news/victory-faq-everything-nwsl-fans-need-to-know-about-the-free-streaming-platform).
